import os
from setuptools import find_packages, setup

with open("README.md", "r") as fh:
    long_description = fh.read()

with open("requirements.txt", "r") as fh:
    install_requires = fh.read().splitlines()

version = "0.0.1"

with open(os.path.join("uetasr", "version.py"), "w") as f:
    f.writelines([
        '"""This file is auto-generated by setup.py, please do not alter."""\n',
        f'__version__ = "{version}"\n',
        "",
    ])

setup(
    name="uetasr",
    version=version,
    description="UETASR: A TensorFlow package for speech recognition",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="thanhtvt & others",
    author_email="trantrongthanhhp@gmail.com",
    packages=find_packages(exclude=["egs*", "tools*", "tests*"]),
    license="MIT",
    keywords=["speech recognition", "tensorflow"],
    install_requires=install_requires,
    python_requires=">=3.8",
    url="https://github.com/thanhtvt/uetasr"
)
